// hand-tuning the layout the model got slightly wrong on xcode
import Foundation

struct ProviderHandler {
    var field0: String = ""
    var field1: String = ""
    var field2: String = ""
    var field3: String = ""
    var field4: String = ""
    var field5: String = ""
    var field6: String = ""
    var field7: String = ""
    var field8: String = ""
    var field9: String = ""
    var field10: String = ""
    var field11: String = ""
    var field12: String = ""
    var field13: String = ""
    var field14: String = ""
    var field15: String = ""
    var field16: String = ""
    var field17: String = ""
    var field18: String = ""
    var field19: String = ""
    var field20: String = ""
    var field21: String = ""
    var field22: String = ""
    var field23: String = ""
    var field24: String = ""
    var field25: String = ""
    var field26: String = ""
}
